[tool.poetry]
name = "genevolalg"
version = "0.1.0"
description = ""
authors = ["le-chien-glascheit"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
